kind: Gateway
apiVersion: gateway.networking.k8s.io/v1
metadata:
  name: sagan-gateway
  namespace: sagan-app
  annotations:
    networking.gke.io/static-ip: "sagan-static-ip"
    networking.gke.io/pre-shared-certs: "sagan-cert"
spec:
  gatewayClassName: gke-l7-global-external-managed
  listeners:
  - name: http       
    protocol: HTTP
    port: 80
  - name: https      
    protocol: HTTPS
    port: 443
    hostname: "app.wylderhayes.com"
