apiVersion: networking.gke.io/v1
kind: ManagedCertificate
metadata:
  name: gke-ingress-cert # match ingress.yaml metadata.annotations.networking.gke.io/managed-certificates
  namespace: default
spec:
  domains:
    - wylderhayes.com  # Replace with your actual domain

